apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: myregistry.com/library/nginx
        name: nginx
        resources: {}
status: {}
