apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: demopod
  name: demopod
spec:
  containers:
  - image: nginx
    name: demopod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
