apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: phpdemo
  name: phpdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpdemo
    spec:
      containers:
      - image: myregistry.com/myproj/phpdemo
        name: phpdemo
      imagePullSecrets:
      - name: regcred
