apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadtest
  name: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
    spec:
      containers:
      - image: quay.io/uvelyster/loadtraffic
        name: loadtraffic
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: loadtest
  labels:
    run: loadtest
spec:
  ports:
  - port: 80
  selector:
    app: loadtest
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loadtest
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadtest
  targetCPUUtilizationPercentage: 50
